./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_00.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_01.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_02.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_03.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_04.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_05.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_06.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_07.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_08.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_09.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_10.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_11.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_12.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_13.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_14.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_15.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_16.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_17.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_18.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_19.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_20.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_21.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_22.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_23.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_24.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_25.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_26.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_27.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_28.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_29.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_30.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_31.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_32.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_33.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_34.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_35.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_36.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_37.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_38.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_39.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_40.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_41.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_42.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_43.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_44.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_45.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_46.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_47.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_48.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_49.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_50.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_51.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_52.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_53.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_54.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_55.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_56.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_57.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_58.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_59.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_60.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_61.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_62.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_63.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_64.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_65.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_66.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_67.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_68.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_69.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_70.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_71.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_72.avi video
./demo_yolov4 ./yolov4_tiny_conf0.1.prototxt ../yolov4_tiny_signate/yolov4_tiny_signate.xmodel ../backup/test_73.avi video
